Repository jssam/Hactoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#1 Update main.java
  Data Structures/Trees/main.java
Labels: hacktoberfest-accepted, hacktoberfest

#2 new commit
  Data Structures/Time and Space/mergesort.java
Labels: hacktoberfest-accepted, accepted

#3 Intersection of Two Linkedlist
  Data Structures/Linked list/Intersection-of-two-linkedlist.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#6 Update and rename insertion sort to insertion sort.java
  Data Structures/Time and Space/insertion sort
  Data Structures/Time and Space/insertion sort.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#7 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#8 Update and rename quick sort to quick sort.java
  Data Structures/Time and Space/quick sort
  Data Structures/Time and Space/quick sort.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#9 Update redixsort.java
  Data Structures/Time and Space/redixsort.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#10 Update merge2sortedarrays.java
  Data Structures/Time and Space/merge2sortedarrays.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#15 Create leetcode.js
  HTML/leetcode scrapper/leetcode.js
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#14 Added BubbleSort.java
  Data Structures/Time and Space/BubbleSort.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#13 Added LinearSearch.java
  LinearSearch.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#12 Create Binary Tree Maximum Path Sum
  Data Structures/Trees/Binary Tree Maximum Path Sum
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#11 Added a program for selection sort
  Data Structures/Time and Space/selection_sort.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#16 Update Linearsearch.java
  Data Structures/Time and Space/Linearsearch.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#20 Articulation Point in Graph
  Data Structures/graph/Articulation Point.cpp
  Data Structures/graph/Bellman Ford.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#19 Create CFQues.js
  HTML/leetcode scrapper/CFQues.js
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#18 Create html.js
  HTML/leetcode scrapper/html.js
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#17 Create promissecques.js
  HTML/leetcode scrapper/promissecques.js
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#22 Bottom View of Binary Tree
  Data Structures/Trees/Bottom View Of A Binarytree.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#23 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#24 Added VerticalSumTree in Java
  .DS_Store
  Data Structures/.DS_Store
  Data Structures/Trees/VerticalSumTree.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#25 whether app
  cloud.svg
  clouds-and-sun.svg
  index.html
  rain.svg
  readme.md
  script.js
  style.css
  thunderstorm.svg
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#26 tree traversals
  Data Structures/Trees/Inorder traversal.cpp
  Data Structures/Trees/Post Order Traversal.cpp
  Data Structures/Trees/Preorder Traversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#27 Delete index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#30 Directory Tree Generator in python
  python project/Directory Tree Generator.py
  python project/readme.md
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#29 Added the XOR Linked List Code
  Data Structures/Linked list/XORLinked.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#28 Added the DFS Algorithm Implementation in cpp
  Data Structures/graph/DFS.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#31 Create merge-K-sortedLL.py
  Data Structures/Linked list/merge-K-sortedLL.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#32 Create rotateList.java
  Data Structures/Linked list/rotateList.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#33 Create All_O'oneDS.java
  Data Structures/Linked list/All_O'oneDS.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#34 Create ReverseNodeInK-Groups.java
  Data Structures/Linked list/ReverseNodeInK-Groups.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#35 Create LFU-Cache.cpp
  Data Structures/Linked list/LFU-Cache.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#37 Create DesignSkiplist.cpp
  Data Structures/Linked list/DesignSkiplist.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#36 Counting Sort Algorithm
  Data Structures/Time and Space/CountingSort.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#38 i created vol_of_sphere.py
  vol_of_sphere.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#39 Insertion sort
  Data Structures/Time and Space/insertionsort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#40 I Created reverse_name.py
  python project/reverse_name.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#41 Laplacian Matrix (Graphs)
  Data Structures/graph/LaplacianMatrix.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#48 Create sub_Array_whoseSumis_Zero.cpp
  Data Structures/ARRAY/sub_Array_whoseSumis_Zero.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#47 Create LinkedListWithRevserseFunc.cpp
  Data Structures/Linked list/LinkedListWithRevserseFunc.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#46 Create first&lastcolor.py
  first&lastcolor.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#45 Added to-do project using javascript
  HTML/todo-app/app.js
  HTML/todo-app/index.html
  HTML/todo-app/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#44 Create generate_list&tuple.py
  generate_list&tuple.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#43 Create greeting.py
  greeting.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#42 Create print_calender.py
  print_calender.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#49 Tic_Tac_Toe_game
  Tic_Tac_Toe_game.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#50 Digital Clock using Python
  python project/digclk.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#51 add snack landing pages
  HTML/snack-landing-page/README.md
  HTML/snack-landing-page/assets/css/aos.css
  HTML/snack-landing-page/assets/css/bootstrap.min.css
  HTML/snack-landing-page/assets/css/style.css
  HTML/snack-landing-page/assets/img/Subscription.png
  HTML/snack-landing-page/assets/img/bg-hero.png
  HTML/snack-landing-page/assets/img/brands.png
  HTML/snack-landing-page/assets/img/hero.png
  HTML/snack-landing-page/assets/img/logo16.png
  HTML/snack-landing-page/assets/img/logo32.png
  HTML/snack-landing-page/assets/img/team.png
  HTML/snack-landing-page/assets/img/user.png
  HTML/snack-landing-page/assets/img/user1.png
  HTML/snack-landing-page/assets/img/user2.png
  HTML/snack-landing-page/assets/img/user3.png
  HTML/snack-landing-page/assets/img/user4.png
  HTML/snack-landing-page/assets/img/user5.png
  HTML/snack-landing-page/assets/js/aos.js
  HTML/snack-landing-page/assets/js/bootstrap.bundle.min.js
  HTML/snack-landing-page/assets/js/jquery-3.5.1.slim.min.js
  HTML/snack-landing-page/index.html
  readme.md
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#54 Miscellany_of_music a project of HTML and CSS
  HTML/Miscellany-of-music/Audio.css
  HTML/Miscellany-of-music/Audio.html
  HTML/Miscellany-of-music/home.css
  HTML/Miscellany-of-music/home.html
  HTML/Miscellany-of-music/homepage.css
  HTML/Miscellany-of-music/im.webp
  HTML/Miscellany-of-music/video.css
  HTML/Miscellany-of-music/video.html
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#53 Create genrate_pattern.cpp
  genrate_pattern.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#52 Add files via upload
  weather/readme.md
  weather/weather.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#64 Added program to check if Euler path exists
  Data Structures/graph/daa_euler_path.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#63 Outdoors landing page
  HTML/Landing Page Outdoors/img/bg.jpg
  HTML/Landing Page Outdoors/img/konohaLogo.png
  HTML/Landing Page Outdoors/index.html
  HTML/Landing Page Outdoors/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#62 Added Tarjan's Algorithm to find strongly connected components in a graph
  Data Structures/graph/Tarjan.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#61 SLL_DeletingAfterAGivenNode.cpp
  Data Structures/Linked list/SLL_DeletingAfterAGivenNode.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#60 alarm using pygame
  alarm/alarm.mp3
  alarm/alarm.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#59 Added a code for printing elements of the matrix in spiral order
  Data Structures/ARRAY/spiral_order_matrix.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#58 Registration form frontend
  reg form/assets/5333978.jpg
  reg form/index.html
  reg form/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#57 Quiz App Added!
  HTML/Quiz Application with Timer/Readme.md
  HTML/Quiz Application with Timer/index.html
  HTML/Quiz Application with Timer/js/questions.js
  HTML/Quiz Application with Timer/js/script.js
  HTML/Quiz Application with Timer/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#56 Joke generator app using JavaScript-AJAX
  Movie Search App - ReactJS/README.md
  Movie Search App - ReactJS/package-lock.json
  Movie Search App - ReactJS/package.json
  Movie Search App - ReactJS/public/index.html
  Movie Search App - ReactJS/public/logo192.png
  Movie Search App - ReactJS/public/manifest.json
  Movie Search App - ReactJS/public/robots.txt
  Movie Search App - ReactJS/src/App.css
  Movie Search App - ReactJS/src/App.js
  Movie Search App - ReactJS/src/components/SearchMovies.jsx
  Movie Search App - ReactJS/src/components/movieCard.jsx
  Movie Search App - ReactJS/src/index.css
  Movie Search App - ReactJS/src/index.js
  joke-generator-app-js/app.js
  joke-generator-app-js/joke app.html
  joke-generator-app-js/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#55 added a date calculator and tile matching game
  python project/datecalculator.py
  python project/tilematchinggame.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#72 Create Triangleproblem.c
  Triangleproblem.c
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#73 Vertical Order Traversal of a Binary Tree (LeetCode)
  Data Structures/Trees/VerticalOrderTraversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#71 Create towerofhanoi.py
  towerofhanoi.py
Labels: hacktoberfest-accepted, accepted

#69 Create Swapping_without_3rd_variable.c
  Swapping_without_3rd_variable.c
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#68 Rock, Paper, Scissors Game.py
  python project/New Text Document.txt
  python project/Rock,Paper ,Scissors game.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#67 Find kth bit in Nth binary string in C++
  Data Structures/Find_Kth_bit.md
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#66 Added a voice recognition in js
  voice_recognition/index.html
  voice_recognition/package-lock.json
  voice_recognition/package.json
  voice_recognition/script.js
  voice_recognition/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#88 Create Binary Search
  Binary Search
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#87 Adding simple Calculator app using HTML & JS
  HTML/simple-calculator/simple-calculator.html
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#86 Added rock-paper-scissor-game
  HTML/rock-paper-scissor-game/bg_game.jpg
  HTML/rock-paper-scissor-game/bg_menu.jpg
  HTML/rock-paper-scissor-game/but_exit.png
  HTML/rock-paper-scissor-game/but_play.png
  HTML/rock-paper-scissor-game/but_solo.png
  HTML/rock-paper-scissor-game/full.html
  HTML/rock-paper-scissor-game/game-section.png
  HTML/rock-paper-scissor-game/i3.png
  HTML/rock-paper-scissor-game/icon.png
  HTML/rock-paper-scissor-game/index.html
  HTML/rock-paper-scissor-game/load.html
  HTML/rock-paper-scissor-game/p1-paper.png
  HTML/rock-paper-scissor-game/p1-rock.png
  HTML/rock-paper-scissor-game/p1-scissors.png
  HTML/rock-paper-scissor-game/p2-paper.png
  HTML/rock-paper-scissor-game/p2-rock.png
  HTML/rock-paper-scissor-game/p2-scissors.png
  HTML/rock-paper-scissor-game/paper-throw.png
  HTML/rock-paper-scissor-game/play.html
  HTML/rock-paper-scissor-game/player1-box.png
  HTML/rock-paper-scissor-game/player2-box.png
  HTML/rock-paper-scissor-game/record-box.png
  HTML/rock-paper-scissor-game/rock-throw.png
  HTML/rock-paper-scissor-game/scissors-throw.png
  HTML/rock-paper-scissor-game/solo.html
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#85 Added Salaray Calculator
  SalaryClaculator.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#84 Create primsAlgorithmUsingPriorityQueue.cpp
  Data Structures/graph/primsAlgorithmUsingPriorityQueue.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#78 hactoberfest2021 binary tree Insertion
  Data Structures/Trees/binary_tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#83 Create kruskalAlgo.cpp
  Data Structures/graph/kruskalAlgo.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#82 Added leetcode 243. Shortest Word Distance
  Data Structures/ARRAY/243. Shortest Word Distance.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#81 Create Sum_of_SubArray.cpp
  Data Structures/ARRAY/Sum_of_SubArray.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#80 Create First_repeating_element_in_array.cpp
  Data Structures/ARRAY/First_repeating_element_in_array.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#79 Create Longest Arithematic Sub Array.cpp
  Data Structures/ARRAY/Longest Arithematic Sub Array.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#77 Added GenericGraph.java
  GenericGraph.java
  readme.md
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#76 Added SelectionSort.cpp and BinarySearch.java
  Data Structures/Time and Space/BinarySearch.java
  Data Structures/Time and Space/SelectionSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#75 Boundary Traversal of a Binary Tree (GfG)
  Data Structures/Trees/BoundaryTraversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#74 added gym website to repo
  Gym Website/.vscode/settings.json
  Gym Website/css/style.css
  Gym Website/img/bg.jpg
  Gym Website/img/logo.jpg
  Gym Website/index.html
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#90 Adding Tic Tac Toe game
  HTML/tic-tac-toe/index.html
  HTML/tic-tac-toe/script.js
  HTML/tic-tac-toe/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#93 stack using python
  python project/stack.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#92 Added Flask hello world app
  python project/flask_app.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#95 Portfolio Home Page is added
  HTML/Portfolio Home Page/index.html
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#94 arrays problem
  Data Structures/ARRAY/Array and average of marks
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#98 Diagonal Traversal of a Binary Tree (GfG)
  Data Structures/Trees/DiagonalTraversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#97 Adding JS Clock
  HTML/lolcat-clock/index.html
  HTML/lolcat-clock/script.js
  HTML/lolcat-clock/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#96 resume bloc react
  resume-bulder-react/.gitignore
  resume-bulder-react/README.md
  resume-bulder-react/package.json
  resume-bulder-react/public/favicon.ico
  resume-bulder-react/public/index.html
  resume-bulder-react/public/logo192.png
  resume-bulder-react/public/logo512.png
  resume-bulder-react/public/manifest.json
  resume-bulder-react/public/robots.txt
  resume-bulder-react/src/App.css
  resume-bulder-react/src/App.test.tsx
  resume-bulder-react/src/App.tsx
  resume-bulder-react/src/blocs/FormData.ts
  resume-bulder-react/src/blocs/SnapshotController.ts
  resume-bulder-react/src/components/Resume/Resume.tsx
  resume-bulder-react/src/components/ResumeForm/ResumeForm.tsx
  resume-bulder-react/src/components/ResumeForm/index.css
  resume-bulder-react/src/components/StreamBuilder.tsx
  resume-bulder-react/src/index.css
  resume-bulder-react/src/index.tsx
  resume-bulder-react/src/logo.svg
  resume-bulder-react/src/react-app-env.d.ts
  resume-bulder-react/src/reportWebVitals.ts
  resume-bulder-react/src/setupTests.ts
  resume-bulder-react/tsconfig.json
  resume-bulder-react/yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#99 Add files via upload
  python project/weather_api.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#100 Added Fizzbuzz.py python program to print fizzbuzz
  fizzbuzz.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#101 DeleteDuplicateElement.java added
  Data Structures/ARRAY/DeleteDuplicateElement.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#106 Adding maze game
  HTML/maze-game/index.html
  HTML/maze-game/script.js
  HTML/maze-game/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#105 Left View of binary tree in cpp
  Data Structures/Trees/Left_View_of_BT.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#104 Added Tik-Tak-Toe-AI
  Tik-Tak-Toe-AI/app.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#103 login
  HTML/login/login.html
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#102 Create Java Array Application for get user inputs
  Array Application for get user inputs
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#108 Create Syntax_Checker_For_CPP.cpp
  Syntax_Checker_For_CPP.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#110 C Program To Print Ascii Value Of Character
  CPP/C_Program_To_Print_Ascii_Value_Of_Character.c
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#107 Array Problem
  Data Structures/ARRAY/BeautifulPath.py
  Data Structures/ARRAY/KadaneAlgo.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#120 Bubble Sort Algorithm
  CPP/Bubble_Sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#119 Array Problems
  Data Structures/ARRAY/CyclicShift.py
  Data Structures/ARRAY/MonkandRotation.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#118 Selection Sort
  CPP/Selection_Sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#117 Code to find minimum and maximum element in an array
  max_min_element.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#116 Knapsack.cpp
  CPP/Knapsack.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#114 Create inspactor.js
  inspactor.js
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#113 To Do app using ReactJS
  Todo-App-React/.gitignore
  Todo-App-React/README.md
  Todo-App-React/package.json
  Todo-App-React/public/favicon.ico
  Todo-App-React/public/favicon.png
  Todo-App-React/public/index.html
  Todo-App-React/public/logo192.png
  Todo-App-React/public/logo512.png
  Todo-App-React/public/manifest.json
  Todo-App-React/public/robots.txt
  Todo-App-React/src/App.css
  Todo-App-React/src/App.js
  Todo-App-React/src/components/Header/AddItem.js
  Todo-App-React/src/components/Header/Header.js
  Todo-App-React/src/components/Todo/List.js
  Todo-App-React/src/components/Todo/Todo.js
  Todo-App-React/src/index.js
  Todo-App-React/yarn.lock
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#112 Added BruteForceAttack.py
  BruteForceAttack.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#111 Translator
  python project/translator.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#121 Right_view_of_BT
  .DS_Store
  Data Structures/Trees/Right_View_of_BT.cpp
  Data Structures/Trees/Vertical Traversal of Binary Tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#133 Sieve Of Eratosthenes solution
  CPP/Sieve_Of_Eratosthenes.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#132 Binary Bucket Sort
  BIN-BUCKET-SORT/README.md
  BIN-BUCKET-SORT/binary_bucket_sort.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#131 Algo to check isomorphic strings
  Isomorphic-Strings.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#135 Gui Based Clock
  python project/Gui_clock.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#129 Added C program to check whether a student passed or failed
  Pass_fail_checker.c
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#128 articulation point and bridges in undirected graph
  articulationpoint_and_bridges_in_graph.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#127 BFS Algorithm Implemented in cpp
  Data Structures/graph/BFS.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#126 Array Stuff
  Data Structures/ARRAY/MonkandInversions.py
  Data Structures/ARRAY/transactions.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#125 Create RemoveCycle.java
  Data Structures/Linked list/RemoveCycle.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#124 Update style.css
  joke-generator-app-js/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#123 Create Electric_car.py
  Electric_car.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#138 Snake Game
  python project/Snake_game.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#137 Graph Traversal using BFS
  CPP/BFS.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#184 Queue implementation using 2 stacks
  queueusing2stacks.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#181 Create Number Guessing Game
  CPP/Number Guessing Game
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#179 youtube video downloader
  youtube video downloader
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#178 Game of Gussing Number
  Data Structures/Game of Gussing Number
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#187 Added Tower of Hanoi Approach
  towerofhanoi.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#177 this is a tic tac toe game
  CPP/BFS.cpp
  Data Structures/Linked list/Implement delete and search an element
  python project/Nqueen_program.py
  python project/Snake_game.py
  python project/Travel_agency_form.py
  python project/insertion_sort.py
  python project/jumping_game.py
  python project/quick_sort.py
  python project/simple_chatbot.py
  python project/snake_game.py
  python project/tic_tac_toe.game.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#176 This is a flappy bird jumping game
  CPP/BFS.cpp
  Data Structures/Linked list/Implement delete and search an element
  python project/Snake_game.py
  python project/Travel_agency_form.py
  python project/insertion_sort.py
  python project/jumping_game.py
  python project/quick_sort.py
  python project/simple_chatbot.py
  python project/tic_tac_toe.game.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#174 Added Conversion of Rupees into Words
  Digits_in_words.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#169 Create Directory.java
  Directory.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#168 Create bank.java
  bank.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#151 Email_Slicer
  python project/Email_Slicer.py
  python project/Face_recognition.py
  python project/GIF_Creator.py
  python project/Number_Gussing.py
  python project/Password_Generator.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#152 GIF_Creator
  CPP/BFS.cpp
  Data Structures/Linked list/Implement delete and search an element
  python project/Email_Slicer.py
  python project/Face_recognition.py
  python project/GIF_Creator.py
  python project/Number_Gussing.py
  python project/Password_Generator.py
  python project/Snake_game.py
  python project/snake_game.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#153 Algo for checking smith number
  Smith-number.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#154 Number_Gussing
  CPP/BFS.cpp
  Data Structures/Linked list/Implement delete and search an element
  python project/Email_Slicer.py
  python project/Face_recognition.py
  python project/GIF_Creator.py
  python project/Number_Gussing.py
  python project/Password_Generator.py
  python project/Snake_game.py
  python project/snake_game.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#155 added selection_sort.py file
  python project/google_image_download.py
  python project/music_player.py
  python project/python-projects/heap_sort.py
  python project/queue.py
  python project/selection_sort.py
  python project/website_blocker.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#161 Create Selection Sort.c
  Data Structures/sorting/Selection Sort.c
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#163 added queue.py file
  python project/google_image_download.py
  python project/music_player.py
  python project/python-projects/heap_sort.py
  python project/queue.py
  python project/selection_sort.py
  python project/website_blocker.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#165 Face_Recognition
  CPP/BFS.cpp
  Data Structures/Linked list/Implement delete and search an element
  python project/Email_Slicer.py
  python project/Face_recognition.py
  python project/GIF_Creator.py
  python project/Number_Gussing.py
  python project/Password_Generator.py
  python project/Snake_game.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#166 Create pattern.java
  pattern.java
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#167 added music_player.py file
  python project/google_image_download.py
  python project/music_player.py
  python project/python-projects/heap_sort.py
  python project/queue.py
  python project/selection_sort.py
  python project/website_blocker.py
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#193 birthDateToCurrentAge.py project added
  python project/birthDateToCurrentAge.py file
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#234 addition calc 1
  addition calc 1
  calc for addition
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#233 Update BoundaryTraversal.cpp
  Data Structures/Trees/BoundaryTraversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#232 Update Binary Tree Maximum Path Sum
  Data Structures/Trees/Binary Tree Maximum Path Sum
Labels: hacktoberfest-accepted, hacktoberfest, accepted

#229 Date_and_Time
  Date_and_Time/index.html
  Date_and_Time/script.js
  Date_and_Time/style.css
Labels: hacktoberfest-accepted, hacktoberfest, accepted
